### ISSUE TITLE
Wrong typing for rich_text

### ISSUE THREAD

**Issue by jacksmethurst** [velsa/notion-ts-client#5]
<img width="1109" alt="Screenshot 2024-07-10 at 15 13 50" src="https://github.com/velsa/notion-ts-client/assets/54802605/e6537a79-0f34-4f5b-bd1b-443a356ab598">

<img width="1034" alt="Screenshot 2024-07-10 at 15 15 30" src="https://github.com/velsa/notion-ts-client/assets/54802605/d9528053-3661-45f6-8eca-7f8f4cbf11ab">

The generated types for a rich_text field should be an array?

**Comment by velsa** [comment]
Yes, there was a bug in the latest version. I've updated the library types from the latest Notion types and unfortunately their types file had a error. They specified `RichTextItemResponse` as type for rich text instead of `RichTextItemResponse[]` 🤦

I've published a fix.

Can you please update to the latest version of notion-ts-client (0.2.10) ?

**Comment by jacksmethurst** [comment]
Started from a clean Next install and unfortunately still get the issue:

<img width="1223" alt="Screenshot 2024-07-11 at 09 31 45" src="https://github.com/velsa/notion-ts-client/assets/54802605/0a3db820-06c5-47c3-ab34-0c8f2460b3ee">

**Comment by velsa** [comment]
Did you run `npx notion-ts-client@latest generate`?

Also, check the file `notion-api.types.ts` in the generated SDK folder under `core/types` and see that the type `TitlePropertyItemObjectResponse` is correct.

**Comment by bmediax** [comment]
On my end, I'm still seeing RichTextItemResponse instead of RichTextItemResponse[], even after using `npx notion-ts-client@latest generate`.

**Comment by bmediax** [comment]
> On my end, I'm still seeing RichTextItemResponse instead of RichTextItemResponse[], even after using `npx notion-ts-client@latest generate`.

Fixed on my side!
